### ISSUE TITLE
IE conflict

### ISSUE THREAD

**Issue by SwordsmanJoe** [Zarathul/simplefluidtanks#13]
From Malte0811 to Zarathul in relation to the following crash
log - https://gist.github.com/SwordsmanJoe/cdee9c58cad568cb49535475ca8d628f
crash - https://gist.github.com/SwordsmanJoe/72a44c79ec93e3517041200cee89646f

@malte0811
This on their side.
@Zarathul please don't package other mods API classes in your mod, for 2 reasons:

It will cause crashes like this one if the mod the API is from is signed (or you decide to sign your mod).
If we update ITool in some way and your version gets loaded first (like it got here) any calls to new methods in ITool would cause some nasty error/crash.

**Comment by Zarathul** [comment]
Looking into it.

**Comment by Zarathul** [comment]
Fixed with 58f52453. Caveats see changelog. Should be available on curse in the next few hours.

**Comment by SwordsmanJoe** [comment]
great to hear :)
