### ISSUE TITLE
Please make hints for waila / hwyla / wawla.

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [Zarathul/simplefluidtanks#14]
Please make hints for waila / hwyla / wawla.

Very cool mod!
But there is very little information about the size of the tank.

**Comment by Zarathul** [comment]
Top (The One Probe) is already supported. It does anything Waila does, and you can make it look exactly like Waila if you prefer that.
I stopped supporting Waila because I want to keep at least a little bit of my sanity and dealing with 3 different versions of the same thing doesn't help.
