### ISSUE TITLE
Hwyla tank info not being updated

### ISSUE THREAD

**Issue by Garagoth** [Zarathul/simplefluidtanks#15]
Hi.

On a clean MC with only:
MC 1.12.2
Forge 14.23.4.2760
Hwyla 1.8.26
Simple Fluid Tanks 1.7.1.1

Build z multiblock tank structure, it forms, can be filled and emptied via valve, but on hwyla tooltip there is no fluid information (it is turned on in hwyla capabilities config) - entirely missing line.

Save & quit to title, then load world again - the tooltip is there, showing proper liquid inside, amount and max capacity. Filling a tank updates amount in hwyla tooltip properly.

Now extend the tank, use wrench to update structure. Liquid inside levels properly, but max capatity in tooltip does not update. However, fluid amount properly updates when adding/removing liquid via a valve. It is possible for a tank tooltip to display amount of liquid inside GREATER then max capacity this way... 

Next, removing block (destroying) from tank and re-forming tank with wrench: there is no liquid inside tank, but tooltip still displays old amount and max capacity... also adding a fluid to tank does not update amount stored displayed in tooltip.

Regards,
Garagoth.

**Comment by Garagoth** [comment]
Just checked with TheOneProbe - it updates properly there in all of above cases...
... but since Hwyla shows _somethig_ it would be good to either display properly or not at all, right now it looks broken.

**Comment by Zarathul** [comment]
Hwyla support was removed in 1.7.0.0 in favor of TheOneProbe. What Hwyla shows is just from it's default implementation.

**Comment by Garagoth** [comment]
Yup, I saw that you removed that part. Default implementation in Hwyla would be sufficient, that is just amount/max and liquid name, just as with tanks from other mods.
My issue is that it sometimes shows tank data in tooltip, but usually is bugged and needs game reload to make it proper (until next tank modification).
Could you look into this please? TOP would still get nice info, but Hwyla users will at least see something basic (that is not broken).

**What is more important:**
Just checked and this issue also affects other mods - like _integrated dynamics_ - to read amounts of fluid inside tanks:
![2018-09-30_23 26 40](https://user-images.githubusercontent.com/916161/46262919-8e250080-c508-11e8-904f-25dfc08bb859.png)

Added fluid reader and 3 monitors: amount, capacity at the bottom row, fluid type on top one.
Then added 3 tanks to the left, used a wrench to update multiblock. TOP updated properly, Hwyla did not... and data on monitors didn't reflect this as well.

**Comment by Zarathul** [comment]
> My issue is that it sometimes shows tank data in tooltip, but usually is bugged and needs game reload to make it proper (until next tank modification).

This happens because the valves TileEntity (and therefore the internal tanks data) is only synced with the client when absolutely necessary for performance reasons (and yes single player has a client and a server). Why the mods you mentioned only look at client data even in single player mode, I don't know. There might be a good reason.
Either way I don't really care.
