### ISSUE TITLE
Can't break blocks while holding an item in the offhand

### ISSUE THREAD

**Issue by Mac15001900** [Zarathul/simplefluidtanks#16]
The wrench doesn't break either the tank or valve blocks while any item (shield, food, or even just a stick) is held in the offhand. It works fine with no offhand items.

Version 1.7.1.1, running with Omnifactory. [Modlist](https://minecraft.curseforge.com/projects/omnifactory/relations/dependencies).

**Comment by Zarathul** [comment]
Thanks for reporting. Fix is ready. New version should be available on Curse pretty soon.
