### ISSUE TITLE
[Omnifactory] Valve showing as empty (to AE2 storage bus) despite full multiblock

### ISSUE THREAD

**Issue by Gombado** [Zarathul/simplefluidtanks#18]
Hey hey,

In omnifactory the valve (bottom bar) shows as empty no matter how full the multiblock tank is.

The interface shows how many buckets are in the tank, but not a fluid value the ae2 storage bus can work with it seems.

**Comment by Zarathul** [comment]
Can confirm there is a problem. Still investigating what's going on.

**Comment by Zarathul** [comment]
Found the problem. Fixed version should go up in the next few hours.

**Comment by Gombado** [comment]
Great stuff Zarathul,

Thanks for the fantastic mod (and the quick solve is impressive too)

![image](https://user-images.githubusercontent.com/34801187/62664715-e6286100-b97c-11e9-818c-adef7ebb49d1.png)

all the best
