### ISSUE TITLE
[1.6.4] A few issues with high-density Storage

### ISSUE THREAD

**Issue by mSt3in** [Zarathul/simplefluidtanks#2]
Consider high values for BucketsPerTank ("BPT") such as 4096 in the following issues.

Valve is clearly using an int (and int math) to store total mb of fluid, and thus has a max capacity of 2^31.  When this limit is reached (added too many tanks) valve reports error and all fluids are lost.  Recommended changing type (and related math) to a long.

Tooltips for Tanks always report total storage of "65536000" even if actual storage is lower.  Tank appears to always report correct percent full. (At a BPT of 4096)

Percent-full tooltip for the Valve will show "0%" when system has a high amount of fluid in it.  I did not notice exactly when the valve stopped calculating percent full correctly....somewhere lower than 20,000,000 mb.  (I believe this issue is purely aesthetic; tool-tip only.)

Request:  Format values with commas.  ie. "20,123,544" instead of "20123544"

Thank you!!!!!

**Comment by mSt3in** [comment]
(Unrelated)  Bonus shot of the massively laggy OpenTank system your mod replaced, thanks to the ability to easily set BucketsPerTank.  (Yes, this server goes through that much lava on a regular basis...it looks great, but...that lag! oh my!)

![2014-05-29_20 53 02](https://cloud.githubusercontent.com/assets/1709008/3140731/e4399276-e937-11e3-9e21-916d049f691b.png)

Shot of the buggy Valve tool-tip.   (BPT = 4096)

![2014-05-31_19 49 41](https://cloud.githubusercontent.com/assets/1709008/3140730/e4373210-e937-11e3-852d-a176622a91cb.png)

Shot of the buggy Tank tool-tip.  (BPT = 4096)

![2014-05-31_19 49 53](https://cloud.githubusercontent.com/assets/1709008/3140732/e43d31ba-e937-11e3-8ce0-872438b88d17.png)

**Comment by Zarathul** [comment]
> Valve is clearly using an int (and int math) to store total mb of fluid, and thus has a max capacity of 2^31. When this limit is reached (added too many tanks) valve reports error and all fluids are lost. Recommended changing type (and related math) to a long. 

The FluidStacks in the Forge Fluid API use int. So nothing I can do about that. 

> Tooltips for Tanks always report total storage of "65536000" even if actual storage is lower. Tank appears to always report correct percent full. (At a BPT of 4096). 

Can't reproduce that. If I set BPT to 4096 the WAILA tooltip shows 4096 B or 4096000 mB as expected. 

> Percent-full tooltip for the Valve will show "0%" when system has a high amount of fluid in it. 

Probably an int overflow. I might be able to fix this.

> Request: Format values with commas. ie. "20,123,544" instead of "20123544"

Will change that for the next version.

**Comment by mSt3in** [comment]
Thank you, and thanks again for your mod; we finished converting every fluid storage tank each of us use late last night and the performance increase of the server is amazing.
