### ISSUE TITLE
Config Capacity change being ignored

### ISSUE THREAD

**Issue by Boolyman** [Zarathul/simplefluidtanks#20]
Hey there,
Using:
MC 1.12.2 
Forge 14.23.5.2847 
Simple Fluid Tanks 1.7.1.3

I changed the configs to have each tank hold 128buckets of fluid.  I built a gallery of multiblock tanks, each with 10 tanks and a valve each.  The multiblocks formed properly, but each multiblock is only registering as holding 352 buckets - which is still the old default capacity of the 10 tanks + valve.  The tank capacity is the only thing I changed in the config.  Is there something I am missing?

**Comment by Zarathul** [comment]
Hmm .. that's definitely a bug. As a workaround, try right-clicking the valves with the wrench. That should update the tanks with the new capacity.
