### ISSUE TITLE
Update of the mod to version 1.15.2 and/or 1.16.x

### ISSUE THREAD

**Issue by Greg-21** [Zarathul/simplefluidtanks#21]
It would be great if you could update this mod to support Minecraft 1.15.2, or (if you prefer) go straight to 1.16.x (of course at first Forge must be released for this version).

**Comment by Zarathul** [comment]
Currently the plan is to wait for 1.16. With 1.15 a lot of rendering stuff changed, which is the most painful part of the mod. Since 1.16 is supposed to change even more in that regard, I gave up on porting to 1.15.2. I really didn't want to wade through that hell twice.

**Comment by Greg-21** [comment]
OK, good to hear that. Thanks for letting me know.
