### ISSUE TITLE
Ore dictionary

### ISSUE THREAD

**Issue by Frontrider** [Zarathul/simplefluidtanks#4]
Use it, if i don't have jabba installed then i won't had the chance to craft anything, because i had forestry bronze (for obvious reasons) and it did not worked. Also, i don't know if you want to restrict to pure green slime, or you want is as glue(i have a few in my storage, and the thing is ore dicted as slimeball).

Its in the 1.6.4 version

**Comment by Zarathul** [comment]
1.6.4 is no longer supported. But I will add ore dictionary support for the 1.7.10 version of the mod. For 1.6.4 I can only suggest to edit your config and change the "ThermalExpansionModId" settings to something random. Then you'll get the default recipes with iron. I realize that's not ideal, but at least you'll be able to craft the blocks.
