### ISSUE TITLE
Use golem doesn't fill bottles

### ISSUE THREAD

**Issue by the-vindex** [Zarathul/simplefluidtanks#6]
I wanted to automate filling of bottles with Use golems. If I direct golem to use empty bottle on the Valve of the tank, which is otherwise functional (player can fill bottle), golem will fill the bottle (I see he holds full bottle), but afterwards bottle disappears. The same setup works ok with other tanks (tested with Sanguimancy Blood Tank).
When I broke Valve and Simple Tank and placed Blood Tank, suddenly a lot of bottles appeared in the world when golem touch Blood Tank.

**Comment by Zarathul** [comment]
Thanks for reporting this issue. I'll look into it.
