### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by PalePyth** [Zarathul/simplefluidtanks#8]
http://pastebin.com/umP6FsEg
Exactly your mod crash me.

**Comment by Zarathul** [comment]
Looks like either someone tempered with my mod and removed the Buildcraft API components or whats more likely, one of the other mods has contains a broken version of the API.
Make sure you only download my mod from here http://minecraft.curseforge.com/mc-mods/simplefluidtanks/.
To narrow the problem down:
- Check if Minecraft starts with only my mod.
- Add the mods from the Modpack you're using one by one until the error reappears.

**Comment by PalePyth** [comment]
It works with the Buildcraft core.

**Comment by Zarathul** [comment]
Guess this is (kinda) resolved then.
